### ISSUE TITLE
iminuit built with more recent dependencies = does not run at Nikhef

### ISSUE THREAD

**Issue by jefftemplon** [NLeSC/root-conda-recipes#26]
Hi,

The root stuff is compiled so that it can run on a CentOS 6 installation.  For some reason, the iminuit package is asking for a version of GLIBC 2.14, which is not present in CentOS 6.  Could you please re-build iminuit with the same dependencies as pyROOT have -- that one doesn't generate errors when imported.

Thanks!

**Comment by remenska** [comment]
@fdiblen @goord Could some of you guys maybe try to build iminuit with our dev-toolbox setup, so it supports older glibc? The one currently in the NLeSC anaconda repository is merely copied from the astropy channel (probably to simplify the XENON1T project so there is only one channel across their conda configs)

**Comment by remenska** [comment]
I have built and uploaded binaries to anaconda cloud (iminuit v1.2 for py2.7/3.4). I don't think I still have push rights here for the recipes, so here goes:

meta.yaml
```
package:
  name: iminuit
  version: "1.2"

source:
  fn: iminuit-1.2.tar.gz
  url: https://pypi.python.org/packages/source/i/iminuit/iminuit-1.2.tar.gz
  md5: 4701ec472cae42015e26251703e6e984
#  patches:
   # List any patch files here
   # - fix.patch

build:
  number: 3
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - iminuit = iminuit:main
    #
    # Would create an entry point called iminuit that calls iminuit.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - iminuit
    - iminuit.frontends
    - iminuit.tests

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/iminuit/iminuit
  license: GNU General Public License (GPL) or MIT License
  summary: 'Interactive Minimization Tools based on MINUIT'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
``` 

build.sh
```
#!/bin/bash

$PYTHON setup.py install 

# Add more build steps here, if they are necessary.

# See
# http://docs.continuum.io/conda/build.html
# for a list of environment variables that are set during the build process.
```
